import { createFileRoute, Link } from "@tanstack/react-router";
import { Mail } from "lucide-react";
import { PageShell } from "@/components/page-shell";
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from "@/components/ui/accordion";

export const Route = createFileRoute("/support")({ head: () => ({ meta: [{ title: "Support — Whispers of Joppa" }, { name: "description", content: "Get help with progress, purchases, Manna, notifications, and your Whispers of Joppa account." }, { property: "og:title", content: "Support — Whispers of Joppa" }, { property: "og:description", content: "Answers and contact information for Whispers of Joppa players." }, { property: "og:type", content: "website" }, { property: "og:url", content: "/support" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/support" }] }), component: SupportPage });
const faqs = [
  ["How do I save my progress?", "Progress saves automatically. To keep it when changing phones, tap the Account button (the person icon) at the top of the board and sign in with Apple, Google, or email."],
  ["I bought something and didn’t receive it.", "Make sure you are signed in (the person icon at the top of the board) and connected to the internet, then restart the game; purchases are delivered automatically. If it still hasn’t arrived, email us from the address linked to your account, with the date of the purchase."],
  ["How do I restore purchases?", "After the opening tutorial, tap your Pearls count to open the shop, then tap Restore purchases."],
  ["How does energy (Manna) work?", "Tapping a generator uses 1 Manna. Manna refills over time."],
  ["How do I turn off notifications?", "Tap the gear at the top of the board and turn the notification switches off."],
] as const;
function SupportPage() { return <PageShell eyebrow="Player care" title="How can we help?" intro="Find quick answers or send us a note. We’re here to help you return to the story."><div className="grid gap-10 md:grid-cols-[.65fr_1.35fr]"><aside className="h-fit border-l-4 border-terracotta bg-card p-6"><Mail className="h-6 w-6 text-terracotta" /><h2 className="mt-4 text-2xl font-semibold text-indigo">Contact us</h2><p className="mt-2 text-sm text-muted-foreground">For account or purchase help, write from the email address linked to your account when possible.</p><a className="mt-4 block font-semibold text-terracotta underline underline-offset-4" href="mailto:support@whispersofjoppa.com">support@whispersofjoppa.com</a></aside><section><h2 className="text-4xl font-semibold text-indigo">Frequently asked questions</h2><Accordion type="single" collapsible className="mt-5">{faqs.map(([question, answer], i) => <AccordionItem key={question} value={`item-${i}`}><AccordionTrigger className="text-base text-indigo">{question}</AccordionTrigger><AccordionContent className="text-muted-foreground">{answer}</AccordionContent></AccordionItem>)}<AccordionItem value="delete"><AccordionTrigger className="text-base text-indigo">How do I delete my account?</AccordionTrigger><AccordionContent className="text-muted-foreground">See the steps on our <Link to="/delete-account" className="font-semibold text-terracotta underline">Delete Account page</Link>.</AccordionContent></AccordionItem></Accordion></section></div></PageShell>; }
